// Generated by LiveScript 1.4.0
(function(){
  var gulp, gulpMarkdown, gulpDebug, gulpUtil, runSequence, colors, paths, renderer;
  gulp = require('gulp');
  gulpMarkdown = require('gulp-markdown');
  gulpDebug = require('gulp-debug');
  gulpUtil = require('gulp-util');
  runSequence = require('run-sequence');
  colors = require('colors');
  paths = {
    markdown: "./posts/*.md"
  };
  renderer = new gulpMarkdown.marked.Renderer();
  renderer.heading = function(text, level){
    var escapedText;
    escapedText = text.toLowerCase().replace(/[^\w]+/g, "-");
    switch (level) {
    case 3:
      return "\n<div style=\"text-align: left; padding: 10px 10px; border-color: #73bc9b; border-width: 0 0 1px 7px; border-style: solid; background: #F8F8F8;margin-top: 2em; margin-bottom: 2em;\"><h" + level + " style=\"text-align: left;\">" + text + "</h" + level + "></div>\n";
    case 4:
      return "\n<h" + level + " style=\"margin-top: 1em; margin-bottom: 1em;\">" + text + "</h" + level + ">\n";
    default:
      return "\n<h" + level + ">" + text + "</h" + level + ">\n";
    }
  };
  renderer.link = function(href, title, text){
    return "<a href=\"" + href + "\" title=\"" + title + "\" rel=\"nofollow\" target=\"_blank\">" + text + "</a>";
  };
  renderer.image = function(href, title, text){
    return "<img src=\"" + href + "\" alt=\"" + text + "\" class=\"alignnone size-medium\" />";
  };
  gulp.task('default', function(){
    return runSequence('markdown', 'watch');
  });
  gulp.task('markdown', function(){
    var options;
    options = {
      breaks: true,
      renderer: renderer,
      pedantic: true
    };
    return gulp.src(paths.markdown).pipe(gulpDebug()).pipe(gulpMarkdown(options)).pipe(gulp.dest('dist'));
  });
  gulp.task('watch', function(cb){
    var options;
    options = {
      interval: 500
    };
    return gulp.watch(paths.markdown, options, function(){
      console.log("Changed Markdown".green);
      return runSequence('markdown');
    });
  });
}).call(this);
